import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function MarketingLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header>
          <p style={{ backgroundColor: "lightblue", padding: "1rem" }}>
            Header
          </p>
        </header>
        {children}
        <footer>
          <p style={{ backgroundColor: "ghostwhite", padding: "1rem" }}>
            Footer
          </p>
        </footer>
      </body>
    </html>
  );
}
